"""initial_schema

Revision ID: 0168038b9c35
Revises:
"""

import sqlalchemy as sa

from alembic import op

revision = "0168038b9c35"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address_line_1", sa.String(length=200), nullable=False),
        sa.Column("address_line_2", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("insurance_provider", sa.String(length=200), nullable=True),
        sa.Column("insurance_member_id", sa.String(length=100), nullable=True),
        sa.Column("preferred_language", sa.String(length=100), nullable=False),
        sa.Column("emergency_contact_name", sa.String(length=100), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "sex IN ('Male', 'Female', 'Other', 'Decline to Answer')", name="ck_sex"
        ),
        sa.CheckConstraint("length(address_line_1) BETWEEN 1 AND 200", name="ck_address"),
        sa.CheckConstraint("length(city) BETWEEN 1 AND 100", name="ck_city"),
        sa.CheckConstraint("length(first_name) BETWEEN 1 AND 50", name="ck_first_name"),
        sa.CheckConstraint("length(last_name) BETWEEN 1 AND 50", name="ck_last_name"),
        sa.CheckConstraint("length(phone_number) = 10", name="ck_phone_length"),
        sa.CheckConstraint("length(state) = 2", name="ck_state_length"),
        sa.CheckConstraint("length(zip_code) IN (5, 10)", name="ck_zip_length"),
        sa.PrimaryKeyConstraint("patient_id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patients_date_of_birth"), ["date_of_birth"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_patients_deleted_at"), ["deleted_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_patients_last_name"), ["last_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_patients_phone_number"), ["phone_number"], unique=False
        )
        batch_op.create_index(
            "uq_active_phone",
            ["phone_number"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL"),
            postgresql_where=sa.text("deleted_at IS NULL"),
        )

    op.create_table(
        "registrations",
        sa.Column("call_id", sa.String(length=100), nullable=False),
        sa.Column("draft", sa.JSON(), nullable=False),
        sa.Column("field_errors", sa.JSON(), nullable=False),
        sa.Column("refusals", sa.JSON(), nullable=False),
        sa.Column("confirmation_token", sa.String(length=36), nullable=True),
        sa.Column("update_patient_id", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("call_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registrations")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_phone",
            sqlite_where=sa.text("deleted_at IS NULL"),
            postgresql_where=sa.text("deleted_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_patients_phone_number"))
        batch_op.drop_index(batch_op.f("ix_patients_last_name"))
        batch_op.drop_index(batch_op.f("ix_patients_deleted_at"))
        batch_op.drop_index(batch_op.f("ix_patients_date_of_birth"))

    op.drop_table("patients")
    # ### end Alembic commands ###
